const chatArea = document.querySelector("#chatArea");
const inputField = document.querySelector("#messageInput");
const sendBtn = document.querySelector("#sendBtn");
//Array with fake users;
const fakeUsers = [
  "Mike",
  "Sarah",
  "Alex",
  "Emma",
  "Ghost",
  "Neo",
  "Pixel",
  "Luna",
  "Ace",
  "Shadow",
  "Nova",
  "Blaze",
  "Kai",
  "Raven",
  "Zero",
  "Jinx",
  "Skye",
  "Milo",
  "Viper",
  "Echo",
  "Storm",
  "Niko",
  "Frost",
  "Daisy",
  "Zane",
  "Ruby",
  "Atlas",
  "Ivy",
  "Cobra",
  "Venom",
  "Orion",
  "Wolf",
  "Sunny",
  "Ash",
  "Bolt",
  "Chloe",
  "Drift",
  "Flame",
  "Hunter",
  "Jade",
  "Knight",
  "Leo",
  "Maverick",
  "Nexus",
  "Onyx",
  "Phoenix",
  "Quest",
  "Rocket",
  "Titan",
  "Violet",
  "Wraith",
  "Yuki",
  "Zen",
  "Byte",
  "Crash",
  "Doom",
  "Faker",
  "Giga",
  "Hazel",
  "Inferno",
  "Jet",
  "Kraken",
  "Logic",
  "Matrix",
  "Nitro",
  "Omega",
  "Proxy",
  "Quasar",
  "Rogue",
  "Sonic",
  "Turbo",
  "Unity",
  "Volt",
  "Whisper",
  "Xeno",
  "Yoshi",
  "Zephyr"
];
//Array with random messages about frontend;
const randomMessages = [
  "JavaScript is actually fun once it clicks",
  "Why does async/await feel like magic sometimes",
  "React hooks saved my life honestly",
  "useEffect dependency array still confuses me",
  "Angular feels too heavy for small projects",
  "TypeScript makes JS feel like a real language",
  "I keep forgetting to type my interfaces in TS",
  "Bootstrap makes UI so fast to prototype",
  "CSS is 10% logic and 90% pain",
  "Flexbox finally makes sense after suffering for days",
  "Grid layout is underrated",
  "Frontend debugging is just console.log everywhere",
  "Why is my state not updating in React",
  "I miss when websites were just HTML and CSS",
  "Vite is insanely fast compared to old setups",
  "Webpack still feels like dark magic",
  "I accidentally broke my layout with one div",
  "Angular change detection is confusing but powerful",
  "React vs Angular debates never end",
  "TypeScript errors sometimes help and sometimes ruin my day",
  "Bootstrap is perfect for quick dashboards",
  "Tailwind changed how I think about styling",
  "I keep forgetting to close JSX tags",
  "Why does my API work in Postman but not in React",
  "Promises inside promises inside promises...",
  "Frontend is easy they said...",
  "Frontend is hard they said...",
  "DOM manipulation feels old school now",
  "I still console.log everything like it's 2010",
  "React re-renders are both amazing and annoying",
  "State management libraries are getting out of control",
  "Redux was scary at first but makes sense now",
  "Zustand feels like a breath of fresh air",
  "Angular services are actually pretty clean",
  "Type safety saves me from so many bugs",
  "JavaScript coercion is still weird",
  "Why does [] + [] equal ''",
  "Frontend interviews are a different kind of stress",
  "I spent 3 hours fixing one CSS bug",
  "Bootstrap breakpoints are actually useful",
  "React component structure is addictive",
  "I love building UI but hate fixing layout bugs",
  "Frontend frameworks evolve faster than I can learn them",
  "Should I learn React or Angular first?",
  "TypeScript generics are confusing but powerful",
  "Hooks rules are simple but easy to break",
  "My app works only in Chrome lol",
  "CORS errors are my worst enemy",
  "Frontend dev is just controlled chaos",
  "Every small change breaks something else",
  "I finally understood props vs state",
  "Why does my button disappear on mobile view",
  "CSS specificity is a silent killer",
  "Bootstrap saved me on deadlines multiple times"
];



